# Generated by Django 4.0.5 on 2022-06-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0004_student_mssv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
