# Generated by Django 4.0.5 on 2022-06-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
